### ISSUE TITLE
Cannot watch .scss-lint.yml

### ISSUE THREAD

**Issue by agross** [chrisrohr/guard-scss_lint#6]
When someone changes .scss-lint.yml I want to run scss_lint for all files in my project.

``` ruby
  guard :scss_lint do
    watch('.scss-lint.yml') { |m| File.dirname(m[0]) }
    watch(%r{\.scss$})
  end
```

Unfortunately, this fails:

```
11:16:08 - ERROR - Guard::ScssLint failed to achieve its <run_on_changes>, exception was:
> [#] Errno::EISDIR: Is a directory @ rb_sysopen - .
> [#] C:/Ruby/lib/ruby/gems/2.2.0/gems/scss_lint-0.43.2/lib/scss_lint/engine.rb:50:in `read'
> [#] C:/Ruby/lib/ruby/gems/2.2.0/gems/scss_lint-0.43.2/lib/scss_lint/engine.rb:50:in `build_from_file'
> [#] C:/Ruby/lib/ruby/gems/2.2.0/gems/scss_lint-0.43.2/lib/scss_lint/engine.rb:21:in `initialize'
> [#] C:/Ruby/lib/ruby/gems/2.2.0/gems/scss_lint-0.43.2/lib/scss_lint/runner.rb:29:in `new'
> [#] C:/Ruby/lib/ruby/gems/2.2.0/gems/scss_lint-0.43.2/lib/scss_lint/runner.rb:29:in `find_lints'
> [#] C:/Ruby/lib/ruby/gems/2.2.0/gems/scss_lint-0.43.2/lib/scss_lint/runner.rb:19:in `block in run'
> [#] C:/Ruby/lib/ruby/gems/2.2.0/gems/scss_lint-0.43.2/lib/scss_lint/runner.rb:18:in `each'
> [#] C:/Ruby/lib/ruby/gems/2.2.0/gems/scss_lint-0.43.2/lib/scss_lint/runner.rb:18:in `run'
> [#] C:/Ruby/lib/ruby/gems/2.2.0/gems/guard-scss_lint-0.1.4/lib/guard/scss_lint.rb:59:in `run'
> [#] C:/Ruby/lib/ruby/gems/2.2.0/gems/guard-scss_lint-0.1.4/lib/guard/scss_lint.rb:50:in `run_on_changes'
```

**Comment by keithlayne** [comment]
I did this:

``` ruby
watch('.scss-lint.yml') { Dir['app/assets/stylesheets/**/*.scss'] }
```

It seems to work fine - just substitute the correct glob for your scss files if it's different.

**Comment by agross** [comment]
@keithlayne Thanks.

Related tools like guard-rspec and guard-haml_lint seem to understand the "directory" `watch` just fine.

**Comment by keithlayne** [comment]
@agross - this has to do with the way the paths/files are fed to `SCSSLint::Runner#run` at https://github.com/chrisrohr/guard-scss_lint/blob/master/lib/guard/scss_lint.rb#L53-L56.

See https://github.com/brigade/scss-lint/blob/v0.43.2/lib/scss_lint/cli.rb#L57-L64 for how it's done in the `SCSSLint::CLI` class - probably not the best place for that logic, but I think pretty much copying that would fix this issue.

Otherwise, this guard will fail with directories - it can be worked around, but you're right, it's inconsistent with other guards in common use.

**Comment by agross** [comment]
@keithlayne Thanks for researching! I changed the block to return all scss files like you suggested.
