### ISSUE TITLE
Automatically trigger all guards when config file is changed

### ISSUE THREAD

**Issue by aspiers** [chrisrohr/guard-scss_lint#8]
This is "problem 1" from [this comment](https://github.com/chrisrohr/guard-scss_lint/issues/7#issuecomment-557942397).

guard-scss_lint knows where the config file lives, so it would be ideal if it automatically retriggered linting of all SCSS guards whenever the config is changed.

Even better if this works when a config file other than the default of `.scss-lint.yml` is used.

**Comment by chrisrohr** [comment]
@aspiers I have pushed 0.1.7.  This fix allows you to add the scss-lint.yml file to your Guardfile.  The guard will now detect that change and if the config changes will re-run on all files.  The guard also ignores the config file when running the actual linter since its not valid scss.  Let me know if this works for you.

**Comment by aspiers** [comment]
Works great, many thanks!!
